### ISSUE TITLE
Feature request: inserting unix milliseconds

### ISSUE THREAD

**Issue by rogierschouten** [jvlad/InsertTimeStamp.vscode.ts#1]
I have a need for inserting the timestamp as unix milliseconds. Is that something your plugin could support?

**Comment by gingerpaledale** [comment]
Now it doesn't support this.
I am glad to upgrade the extension for you. Please, provide me examples of what "timestamp as unix milliseconds" actually is.   

What exact output do you expect to get?

##### Write me something like this:

```
For time moment of value "Oct 27 2017 11:44"  
I want to get "xxxx"
as the result of insertion.
```

Replace _xxxx_ with what you actually want to get at the moment of _Oct 27 2017 11:44_.

For more confidence, you can write several examples like that one is mentioned above but for the moments of time other than _Oct 27 2017 11:44_.

**Comment by rogierschouten** [comment]
Hi @jvlad, thank you for your positive answer. 

A unix timestamp is the number of seconds since January 1st, 1970.   On Linux, you can retrieve it by typing `date +%s` on the command line.  It is often used in program code to represent a timestamp in a compact way. 

Javascript adds to this by having unix milliseconds rather than seconds, i.e. the milliseconds since January 1st, 1970.  You can retrieve this with a JavaScript Date.valueOf() call.  See also https://currentmillis.com/

Therefore, 

```
For time moment of value "Oct 27 2017 11:44"  
I want to get "1477561440000"
as the result of insertion.
```

Or with fractional seconds:

```
For time moment of value "Oct 27 2017 11:44:01.666"  
I want to get "1477561441666"
as the result of insertion.
```

**Comment by jvlad** [comment]
Now it doesn't support this.

I am glad to upgrade the extension for you. Please, provide me examples of
what "timestamp as unix milliseconds" actually is. What exact output do you
expect to get?

Write me something like this:
------------------------
For time moment of value "Oct 27 2017 11:44" I want to get "xxxx" as the
result of insertion.
------------------------

Replace <xxxx> with what you actually want to get at the moment of Oct 27
2017 11:44.

For more confidence, you can write several examples like that one is
mentioned above but for the moments of time other than Oct 27 2017 11:44.

Thanks for your interest.

-- 
Vlad Zamskoi.
+972 53 306-5004

I am Android developer.
You can learn more about me on www.freeraven.com page.

**Comment by rogierschouten** [comment]
I think something went wrong with your last message, I just sent you the examples in the format you wanted them. If you go to this thread on GitHub you'll see what I mean

**Comment by gingerpaledale** [comment]
Status:
in progress

Estimate:
5h

Release deadline:
Tue Nov 1 23:00:00 IDT 2016

**Comment by zvlades** [comment]
Won't meet the deadline

**Comment by zvlades** [comment]
Won't meet the deadline.

**Comment by rogierschouten** [comment]
Hi @zvlades or @jvlad, any idea on new deadline?

**Comment by gingerpaledale** [comment]
Will answer today untill 22.

Thanks again for you interest.

## 

Vlad Zamskoi.
​+​972 53 306-5004

I am Android developer;
you can learn more about me on freeraven.com page.

**Comment by gingerpaledale** [comment]
Next deadline:

Sat Nov 12 11:00 IDT 2016

## 

Vlad Zamskoi.
​+​972 53 306-5004

I am Android developer;
you can learn more about me on freeraven.com page.

**Comment by rogierschouten** [comment]
Hi @zvlades or @jvlad, any idea on new deadline? Or did you release it already?

**Comment by rogierschouten** [comment]
Hi all, 

This has already been solved by the 'Insert Date String' plugin.
